apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor
spec:
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
      - name: conversor
        image: jp0user0docker/conversao-temperatura:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
